#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "yuno-archive"
name = "Yuno Archive"
description.en = "Extend functionnality of built-in yunoHost backup system"
description.fr = "Étend les fonctionnalités du backup fourni par YunoHost en permettant la sauvegarde auto à intervales régulières et l'envoi sur distant via Rclone"

version = "0.3.0~ynh1"

maintainers = ["Mistermasque"]

[upstream]
license = "AGPL-3.0-only"
code = "https://github.com/Mistermasque/yuno-archive"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "500M"
ram.runtime = "50M"

[install]
    [install.save_data]
    ask.en = "Should backup emails and user home directories?"
    ask.fr = "Doit-on sauvegarder les mails et les répertoires (home) des utilisateurs ?"
    type = "boolean"
    default = true

    [install.save_apps]
    ask.en = "Which apps should backup?"
    ask.fr = "Quelles applications doivent être sauvegardées ?"
    help.en = "App list separated by comma. You can write 'all' to select all apps, even those installed after this borg app. You can also select all apps but some apps by writing 'exclude:' following by an app list separated by comma."
    help.fr = "Liste d'applications séparées par des virgules. Vous pouvez écrire 'all' pour sélectionner toutes les apps, même celles installées après cette application borg. Vous pouvez aussi sélectionner toutes les apps sauf certaines en écrivant 'exclude:' suivi d'une liste d'applications séparées par des virgules."
    type = "string"
    default = "all"

    [install.on_calendar]
    ask.en = "When and at which frequency should the backups be performed?"
    ask.fr = "Quand et à quelle fréquence les sauvegardes doivent-elles être effectuées ?"
    type = "string"
    help = "For example: `Monthly`, `Weekly`, `Daily` (=every day at midnight), `Hourly`, `Sat *-*-1..7 18:00:00` (=the first saturday of every month at 18:00), `4:00` (=every day at 4 AM), `5,17:00` (=every day at 5 AM and 5 PM). See the [systemd OnCalendar format for full syntax doc](https://wiki.archlinux.org/index.php/Systemd/Timers#Realtime_timer)"
    default = "Daily"

    [install.mailalert]
    ask.en = "Do you want admin to receive email notifications on backups?"
    ask.fr = "Souhaitez-vous que les administrateurs reçoivent des notifications par e-mail à chaque sauvegarde ?"
    type = "select"
    choices = ["always", "errors_only", "never"]
    default = "errors_only"

[resources]
    [resources.sources.main]
    url = "https://github.com/Mistermasque/yuno-archive/archive/refs/tags/0.3.0.tar.gz"
    sha256 = "c20b97820b46bc855b92e69327cad1b66ca7913c2dd20305baedbc8021ddd7f0"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
