#!/usr/bin/env bash

# Script used to launch yunohost backup method according to configuration
# It prepares options for backup method (elements to save)

source "__INSTALL_DIR__/script_helpers"


#=========================================================#
#                           MAIN                          #
#=========================================================#

is_verbose=false
if [[ $( get_conf debug ) == "1" ]]; then
    is_verbose=true
fi

# system hooks methods setted with configuration
declare -a system=()

# Add system hooks according to configuration
if [[ $( get_conf save_system_conf ) == "1" ]]; then
    log "Conf enabled, add to backup script..."

    for hook in $(filter_hooks conf); do
        system+=("$hook")
        log "- Hook '$hook' added"
    done
fi

# Add data hook according to configuration (without data_multimedia hook)
if [[ $( get_conf save_data ) == "1" ]]; then
    log "Data enabled, add to backup script..."

    for hook in $(filter_hooks data | grep -v 'data_multimedia'); do
        system+=("$hook")
        log "- Hook '$hook' added"
    done
fi

# Add data multimedia according to configuration
if [[ $( get_conf save_data_multimedia ) == "1" ]]; then
    log "Data multimedia enabled, add to backup script..."
    disable_nobackup_multimedia

    system+=("data_multimedia")
    log "- Hook 'data_multimedia' added"
fi

# Add apps according to configuration
declare -a apps=()
save_apps=$( get_conf save_apps | tr -d ' ' )
log "Add apps to backup script..."
for application in $(sudo ls /etc/yunohost/apps/); do

    if ([[ "$save_apps" =~ ^exclude: ]] && grep -wq "$application" <<<"$save_apps") ||
        ([[ "$save_apps" != "all" ]] && [[ ! "$save_apps" =~ ^exclude: ]] && ! grep -wq "$application" <<<"$save_apps"); then
        continue
    fi

    if sudo test ! -f "/etc/yunohost/apps/$application/scripts/backup"; then
        log "[WARN] The application $application has no backup script. This app won't be backed up."
        continue
    fi

    apps+=("$application")
    log "- App '$application' added'"
done

if [[ ${#apps[@]} -eq 0 && ${#system[@]} -eq 0 ]]; then
    log_error "[WARN] apps and system are empty, nothing to save."
    exit 0
fi
# Define apps option
apps_option=""
if [[ ${#apps[@]} -ne 0 ]]; then
    apps_option=" --apps ${apps[*]}"
fi

# Define system option
option_system=""
if [[ ${#system[@]} -ne 0 ]]; then
    option_system=" --system ${system[*]}"
fi

current_date=$(date +"%Y%m%d-%H%M%S")
if $is_verbose; then
    log "yunohost backup create --name '${current_date}___APP__' --method '__APP___app' $option_system $apps_option"
fi

execute_cmd sudo yunohost backup create --name "${current_date}___APP__" --method "__APP___app" "$option_system" "$apps_option"
exit $?