#!/usr/bin/env bash

# This script is called by the systemd service to launch backup or send according to configuration

source "__INSTALL_DIR__/script_helpers"

#=========================================================#
#                     GLOBAL VARS                         #
#=========================================================#

# Script name and path
THIS_SCRIPT=$(readlink -f "${BASH_SOURCE[0]}")
readonly THIS_SCRIPT

# Backup script
readonly BACKUP_SCRIPT="__INSTALL_DIR__/backup"

# Send script
readonly SEND_SCRIPT="__INSTALL_DIR__/send"

#=========================================================#
#                    SCRIPT FUNCTIONS                     #
#=========================================================#

### FUNCTION BEGIN
# Usage function to show help message
# OUTPUTS:
# 	Print help message to stdout
### FUNCTION END
usage() {
    cat <<MSG_USAGE
Script used to launch Yuno-archive according to configuration

Usage  :
   $(basename "$0") [Options]


Options :
   -h : Show this message
   -f : Force script execution (do not check if there is another instance running)
MSG_USAGE
}

#=========================================================#
#                           MAIN                          #
#=========================================================#
while getopts "fh" option; do
    case "${option}" in
    h)
        usage
        exit 0
        ;;
    f)
        FORCE=true
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

# This is a hack to avoid executing script during ar backup or just after it.
# For an obscure reason, the script is executed by systemd just after an update
# We use FORCE to by pass this check
if [[ ! $FORCE ]]; then
    if is_updating_or_running; then
        log_error "[ERROR] There is another backup process running or app in updating state. Abord.\nIf the problem persist after reboot, call '$THIS_SCRIPT' with -f option"
        # We send mail in this only if debug is true
        if [[ $( get_conf debug ) == "1" ]]; then
            send_mail
        else
            # Don't forget to delete temp file (send_mail do it)
            rm -f "$MAIL_LOG_FILE"
        fi
        
        exit 1
    fi
fi

method="$( get_conf_method )"

# Add a line to log file in order to identify automatic launch
sudo echo "---------- START ${method} FROM ${THIS_SCRIPT} -----------" | tee -a "${YUNO_ARCHIVE_LOG_FILE}"

now="$(date "+%Y-%m-%d %H:%M:%S")"
log "START ${method} for  __APP__ at ${now}"

case "$method" in
send_to_drive | send_to_rclone | send_to_scp)
    "$SEND_SCRIPT" || true
    ;;
*)
    "$BACKUP_SCRIPT" || true
    ;;
esac

# Add a line to log file in order to identify automatic launch
sudo echo "---------- END ${method} FROM ${THIS_SCRIPT} -----------" | tee -a "${YUNO_ARCHIVE_LOG_FILE}"

now="$(date "+%Y-%m-%d %H:%M:%S")"
log "END ${method} for  __APP__ at ${now}"

send_mail
