#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

state="fresh install"
ynh_app_setting_set --key=state --value="$state"
last_run="-"
ynh_app_setting_set --key=last_run --value="$last_run"
ynh_app_setting_set --key=ynh_repo --value="1"
ynh_app_setting_set --key=method --value="local"
ynh_app_setting_set --key=keep --value="all"
ynh_app_setting_set --key=local_repository --value=""
ynh_app_setting_set --key=drive_repository --value=""
ynh_app_setting_set --key=rclone_repository --value=""
ynh_app_setting_set --key=save_system_conf --value="1"
ynh_app_setting_set --key=save_data_multimedia --value="0"

#=================================================
# INSTALL RCLONE
#=================================================
ynh_script_progression "Installing Rclone..."

install_rclone

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"
chmod ug+rx "$install_dir/yuno-archive.sh"

#=================================================
# SPECIFIC SETUP
#=================================================
# SETUP THE BACKUP METHOD
#=================================================
ynh_script_progression "Setting up backup method..."

mkdir -p /etc/yunohost/hooks.d/backup_method

ynh_config_add --template="backup_method" --destination="/etc/yunohost/hooks.d/backup_method/10-${app}_app"
chmod go=--- "/etc/yunohost/hooks.d/backup_method/10-${app}_app"

ynh_config_add --template="backup" --destination="$install_dir/backup"
chown "$app:$app" "$install_dir/backup"
chmod ug+rx "$install_dir/backup"

ynh_config_add --template="sudoer" --destination="/etc/sudoers.d/$app"
chown root:root "/etc/sudoers.d/$app"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add $app --description="Yuno Archive" --test_status="systemctl show $app.service  -p ActiveState --value | grep -v failed" --log "/var/log/$app/backup.log"
# Disable the service, this is to prevent the service from being triggered at boot time
ynh_hide_warnings ynh_systemctl --service="$app" --action="disable"

# Configure the systemd timer
ynh_config_add --template="systemd.timer" --destination="/etc/systemd/system/$app.timer"
ynh_systemctl --service="$app.timer" --action="enable"
ynh_systemctl --service="$app.timer" --action="start"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

mkdir -p "/var/log/$app"
chown -R $app:$app "/var/log/$app"
chmod u+w "/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
