#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================
ynh_script_progression "Stopping service related to $app..."
ynh_systemctl --service="$app" --action="stop"

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null; then
    ynh_script_progression "Removing $app service integration..."
    yunohost service remove "$app"
fi

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_systemctl --service="$app.timer" --action="stop"
ynh_hide_warnings ynh_systemctl --service="$app.timer" --action="disable"
ynh_config_remove_systemd

ynh_safe_rm "/etc/systemd/system/$app.timer"
ynh_safe_rm "/etc/yunohost/hooks.d/backup_method/10-${app}_app"
ynh_safe_rm "/etc/sudoers.d/$app"

# Remove logrotate to manage application logfile(s)
ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
