#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null; then
    ynh_script_progression --message="Removing $app service integration..."
    yunohost service remove $app
fi

#=================================================
# REMOVE RCLONE
#=================================================
# ynh_script_progression --message="Removing Rclone..."

# remove_rclone

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

systemctl stop $app.timer
systemctl disable $app.timer --quiet
ynh_remove_systemd_config

ynh_secure_remove --file="/etc/systemd/system/$app.timer"
ynh_secure_remove --file="/etc/yunohost/hooks.d/backup_method/10-${app}_app"
ynh_secure_remove --file="/etc/sudoers.d/$app"

# Remove logrotate to manage application logfile(s)
ynh_remove_logrotate

# remove log files
ynh_secure_remove --file="/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
