#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL RCLONE
#=================================================
ynh_script_progression "Reinstalling Rclone..."

install_rclone

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chmod ug+rx "$install_dir/yuno-archive.sh"
chmod ug+rx "$install_dir/backup"
chmod ug+rx "$install_dir/backup_hook"
chmod ug+rx "$install_dir/send"
chmod ug+rx "$install_dir/systemd_start"
chmod +r "$install_dir/script_helpers"

#=================================================
# RESTORE BACKUP METHODS
#=================================================
ynh_script_progression "Setting up backup method..."

mkdir -p /etc/yunohost/hooks.d/backup_method

ynh_restore "/etc/yunohost/hooks.d/backup_method/10-${app}_app"
chmod go=--- "/etc/yunohost/hooks.d/backup_method/10-${app}_app"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/$app.service"
# Disable the service, this is to prevent the service from being triggered at boot time
systemctl disable "${app}.service" --quiet --now
yunohost service add $app --description="Yuno Archive" --test_status="systemctl show $app.service -p ActiveState --value | grep -v failed" --log "/var/log/$app/backup.log"

ynh_restore "/etc/systemd/system/$app.timer"
ynh_systemctl --service="$app.timer" --action="enable"
ynh_systemctl --service="$app.timer" --action="start"

# Do not restore log files, just create dir
mkdir -p "/var/log/$app"
chown -R $app:$app "/var/log/$app"
chmod u+w "/var/log/$app"

# Restore logrotate file
ynh_restore "/etc/logrotate.d/$app"

# Restore the sudoers file
ynh_restore "/etc/sudoers.d/$app"
chown root:root "/etc/sudoers.d/$app"

#=================================================
# RCLONE CONFIGURATION
#=================================================

# Restore rclone configuration
ynh_restore "/root/.config/rclone"
if [[ -e  "/root/.config/rclone" ]]; then
    chown root:root "/root/.config/rclone"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
