#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL RCLONE
#=================================================
ynh_script_progression --message="Reinstalling Rclone..."

install_rclone


#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..." --weight=1

ynh_restore_file --origin_path="$install_dir"

chmod +rx "$install_dir"

#=================================================
# RESTORE BACKUP METHODS
#=================================================
ynh_script_progression --message="Setting up backup method..." --weight=1

mkdir -p /etc/yunohost/hooks.d/backup_method

ynh_restore_file --origin_path="/etc/yunohost/hooks.d/backup_method/10-${app}_app"
chmod go=--- "/etc/yunohost/hooks.d/backup_method/10-${app}_app"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
yunohost service add $app --description="Yuno-archive extends Yunohost backup system" --test_status="systemctl show $app.service  -p ActiveState --value | grep -v failed" --log "/var/log/$app/borg.log"
# Disable the service, this is to prevent the service from being triggered at boot time
systemctl disable $app.service --quiet

ynh_restore_file --origin_path="/etc/systemd/system/$app.timer"
systemctl enable $app.timer --quiet
systemctl start $app.timer

# Do not restore log files, just create dir
mkdir -p "/var/log/$app"
chown -R $app:$app "/var/log/$app"
chmod u+w "/var/log/$app"


# Restore logrotate file
ynh_restore_file --origin_path="/etc/logrotate.d/$app"

# Restore the sudoers file
ynh_restore_file --origin_path="/etc/sudoers.d/$app"


#=================================================
# RCLONE CONFIGURATION
#=================================================

# Restore rclone configuration
ynh_backup --not_mandatory --origin_path="/root/.config/rclone"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
