#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="${app}.timer" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set --key="state" --value="updating"
ynh_app_setting_set --key="last_run" --value="-"
ynh_app_setting_set_default --key=debug --value=0

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

chmod ug+rx "$install_dir/yuno-archive.sh"

#=================================================
# UPGRADE RCLONE
#=================================================
ynh_script_progression "Upgrading Rclone..."

install_rclone

#=================================================
# SETUP THE BACKUP METHOD
#=================================================
ynh_script_progression "Setting up backup method..."

mkdir -p /etc/yunohost/hooks.d/backup_method

ynh_config_add --template="backup_method" --destination="/etc/yunohost/hooks.d/backup_method/10-${app}_app"
chmod go=--- "/etc/yunohost/hooks.d/backup_method/10-${app}_app"

#=================================================
# INSTALL BACKUP SERVICE SCRIPT
#=================================================
ynh_script_progression "Setting up backup service script..."

ynh_config_add --template="backup" --destination="$install_dir/backup"
chown "$app:$app" "$install_dir/backup"
chmod ug+rx "$install_dir/backup"

ynh_config_add --template="backup_hook" --destination="$install_dir/backup_hook"
chown "$app:$app" "$install_dir/backup_hook"
chmod ug+rx "$install_dir/backup_hook"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated systemd config
ynh_config_add --template="systemd.service" --destination="/etc/systemd/system/${app}.service"
# Disable the service, this is to prevent the service from being triggered at boot time
systemctl disable "${app}.service" --quiet --now
yunohost service add $app --description="Yuno Archive" --test_status="systemctl show $app.service -p ActiveState --value | grep -v failed" --log "/var/log/$app/backup.log"

ynh_config_add --template="systemd.timer" --destination="/etc/systemd/system/$app.timer"
ynh_systemctl --service="$app.timer" --action="enable"

ynh_config_add --template="sudoer" --destination="/etc/sudoers.d/$app"
chown root:root "/etc/sudoers.d/$app"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

mkdir -p "/var/log/$app"
chown -R $app:$app "/var/log/$app"
chmod u+w "/var/log/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app.timer" --action="start"

#=================================================
# END OF SCRIPT
#=================================================
# Update state
ynh_app_setting_set --key="state" --value="not run since last update"
ynh_script_progression "Upgrade of $app completed"
